language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

before_install:
  - sudo apt-get update

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev


before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/v31.tar.gz -O v31.tar.gz &&
  tar xzf v31.tar.gz &&
  cd kcov-31 &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-master &&
  cargo install cargo-kcov --verbose &&
  cargo kcov --verbose --coveralls &&
  ./cc-test-reporter format-coverage -t cobertura target/cov/kcov-merged/cobertura.xml &&
  ./cc-test-reporter upload-coverage &&
  echo "Uploaded code coverage"