name: Coverage test and upload to Codecov/Coveralls

on: [push, pull_request]

jobs:
  test:
    name: Coverage test
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --tests --examples --doc --no-fail-fast --timeout 240 --coveralls ${{ secrets.COVERALLS_TOKEN }} --out Xml 

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}} # not required for public repos
          fail_ci_if_error: true